#!/bin/sh
# periodically print date and load average to the bar

xwrite() {
file="$1"; shift
echo -n "$@" | wmiir write "$file"
}

wmiir remove /bar/mpdstatus 2>/dev/null && sleep 2
wmiir create /bar/mpdstatus
xwrite /bar/mpdstatus/colors $WMII_NORMCOLORS

while xwrite /bar/mpdstatus/data `mpc | head -n1`
do
sleep 3
done &

# This is the important part; watching /event for label clicks
wmiir read /event 2> /dev/null |
while read event
do
set -- $event
if test "$2" = "mpdstatus"
then
case "$3" in
1)
mpc prev
xwrite /bar/mpdstatus/data `mpc | head -n1`
;;
2) mpc toggle;;
3)
mpc next
xwrite /bar/mpdstatus/data `mpc | head -n1`
;;
esac
fi
done