#!/bin/sh
# configure wmii


xwrite() {
	file="$1"; shift
	echo -n "$@" | wmiir write "$file"
}

proglist() {
	ls -lL "$@" 2>/dev/null | awk 'NF>2 && $1 ~ /^[^d].*x/ {print $NF}' | sort -u
}

# Tagging
wmiir write /def/rules <<EOF
/Ekiga.*/ -> ~
/Gaim.*/ -> ~
/Gimp.*/ -> ~
/MPlayer.*/ -> ~
/.*/ -> !
/.*/ -> 1
EOF


# MISC
xsetroot -solid '#333333'
PROGS_FILE=/tmp/.wmiimenu.$USER.proglist
proglist `echo "$PATH" | tr : ' '` >$PROGS_FILE &

WMII_FONT='-artwiz-glispbold-*-*-*-*-*-*-*-*-*-*-*-*'
WMII_SELCOLORS='#FFFFFF #248047 #147027'
WMII_NORMCOLORS='#4D4E4F #DDDDAA #FFFFCC'
# dark background
#WMII_NORMCOLORS='#e0e0e0 #0a0a0a #202020'

export WMII_FONT WMII_NORMCOLORS WMII_SELCOLORS PROGS_FILE

export MPD_HOST=philisha.net

# WM CONFIGURATION
xwrite /def/border 1
xwrite /def/font $WMII_FONT
xwrite /def/selcolors $WMII_SELCOLORS
xwrite /def/normcolors $WMII_NORMCOLORS
xwrite /def/colmode stack
xwrite /def/colwidth 0


~/.wmii-3/status &
~/.wmii-3/mpd &



emacs-snapshot -l ~/.emacs.d/wmii.el &
epiphany &

exit


# EVENT LOOP
wmiir read /event 2>/dev/null |
while read event
do
	set -- $event
	type="$1"; shift
	case "$type" in
	Start)
		if test wmiirc = "$1"
		then
			exit
		fi;;
	BarClick)
		xwrite /ctl view ''"$1"'';;
	Key)
		case "$1" in
		$MODKEY-$LEFT)
			xwrite /view/ctl select prev;;
		$MODKEY-$RIGHT)
			xwrite /view/ctl select next;;
		$MODKEY-$DOWN)
			xwrite /view/sel/ctl select next;;
		$MODKEY-$UP)
			xwrite /view/sel/ctl select prev;;
		$MODKEY-space)
			xwrite /view/ctl select toggle;;
		$MODKEY-d)
			xwrite /view/sel/mode default;;
		$MODKEY-s)
			xwrite /view/sel/mode stack;;
		$MODKEY-m)
			xwrite /view/sel/mode max;;
		$MODKEY-a)
			PATH=$HOME/.wmii-3:/usr/local/etc/wmii-3:$PATH `proglist /usr/local/etc/wmii-3 $HOME/.wmii-3 | wmiimenu` &;;
		$MODKEY-p)
			wmiisetsid `wmiimenu <$PROGS_FILE` &;;
		$MODKEY-t)
			xwrite /ctl view "`wmiir read /tags | wmiimenu`" &;;
		$MODKEY-[0-9])
			xwrite /ctl view `echo $1 | sed 's/.*-//'`;;
		$MODKEY-Return)
			xterm &;;
		$MODKEY-Shift-$LEFT)
			xwrite /view/sel/sel/ctl sendto prev;;
		$MODKEY-Shift-$RIGHT)
			xwrite /view/sel/sel/ctl sendto next;;
		$MODKEY-Shift-$DOWN)
			xwrite /view/sel/sel/ctl swap down;;
		$MODKEY-Shift-$UP)
			xwrite /view/sel/sel/ctl swap up;;
		$MODKEY-Shift-space)
			xwrite /view/sel/sel/ctl sendto toggle;;
		$MODKEY-Shift-c)
			xwrite /view/sel/sel/ctl kill;;
		$MODKEY-Shift-t)
			xwrite /view/sel/sel/tags ''"`wmiir read /tags | wmiimenu`"'' &;;
		$MODKEY-Shift-[0-9])
			xwrite /view/sel/sel/tags `echo $1 | sed 's/.*-//'`;;
		esac;;
	esac
done &
