{ 'emacs' : { 'fresh': ['cvs -z3 -d:pserver:anonymous@cvs.savannah.gnu.org:/cvsroot/emacs co emacs',
                        'cd emacs',
                        './configure',
                        'make bootstrap',
                        'make',
                        'sudo make install'],
              'update': ['cd emacs',
                         'cvs up',
                         'make bootstrap',
                         'make',
                         'sudo make install'] },

  'screen' : { 'fresh': ['cvs -z3 -d:pserver:anonymous@cvs.savannah.gnu.org:/sources/screen co screen',
                        'cd screen',
                        './configure',
                        'make',
                        'sudo make install'],
              'update': ['cd screen',
                         'cvs up',
                         'make',
                         'sudo make install'] },

  'ruby' : { 'fresh': ['svn co http://svn.ruby-lang.org/repos/ruby/trunk ruby',
                       'cd ruby',
                       'autoconf',
                       './configure --program-suffix=1.9',
                       'make',
                       'sudo make install'],
            'update': ['cd ruby',
                       'svn up',
                       'make',
                       'sudo make install'] },
  'ruby-dbus' : { 'fresh': ['svn co svn://trac.luon.net/ruby-dbus/trunk ruby-dbus',
                            'cd ruby-dbus',
                            './configure',
                            'make',
                            'sudo make install'],
                  'update': ['cd ruby-dbus',
                             'svn up',
                             'make',
                             'sudo make install'] },
  'rubinius' : { 'fresh': ['git clone git://git.rubini.us/code rubinius',
                           'cd rubinius',
                           'rake build',
                           'sudo rake install'],
                 'update': ['cd rubinius',
                            'git pull',
                            'rake rebuild',
                            'sudo rake install']},
  'mpd' : { 'fresh': ['svn co https://svn.musicpd.org/mpd/trunk mpd',
                      'sudo apt-get build-dep mpd',
                      'sudo apt-get install libmp4v2-dev libfaad2-0 automake',
                      'cd mpd',
                      './autogen.sh',
                      './configure',
                      'make',
                      'sudo make install'],
            'update': ['cd mpd',
                       'svn up',
                       './configure',
                       'make',
                       'sudo make install']}
}